apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  selector:
    app: spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: kwangjong/spark-stream-processor